import type {NextPage} from "next";
import Link from "next/link";

import Layout from "../components/Layout";

const Home: NextPage = () => {
    return (
        <Layout
            title="Counter with mobx,ts"
            description="Generated by create next app">
            <main>
                <Link href="/count">카운터</Link>
            </main>
            <footer></footer>
        </Layout>
    );
};

export default Home;
