// modules
import {observer} from "mobx-react-lite";
import React, {useContext} from "react";
import {StoreContext} from "../stores";

// components
import Layout from "../components/Layout";

const CountPage: React.FC = () => {
    const counterStore = useContext(StoreContext).counterStore;

    return (
        <Layout
            title="Counter with mobx,ts"
            description="Generated by create next app">
            <h1>Counter: {counterStore.count}</h1>
            <button onClick={() => counterStore.increase()}>Increase</button>
            <button onClick={() => counterStore.decrease()}>Decrease</button>
        </Layout>
    );
};

export default observer(CountPage);
